openapi: 3.0.0
info:
  title: Tshirt store API
  description: API's for Tshirt ecom store
  version: 1.0.1
  contact:
    email: dhaneshacad@gmail.com
    url: "https://lco.dev"

# servers:
#   - url: http://localhost:4000/api/v1
#     description: localhost version of our app
#   - url: https://localhost:4000/api/v1
#     description: this is just dummy api url, it doesn't work

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host - secure
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http



components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: returns a greet message
      responses:
        200:
          description: All good and success
          content: 
            application/json:
              schema: 
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error

